%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width:  848
image_height: 480
distortion_parameters:
  # from "/camera/infra1/camera_info" (RealSense factory calibration data)
  k1: 0.0
  k2: 0.0
  p1: 0.0
  p2: 0.0
projection_parameters:
  # from "/camera/infra1/camera_info" (RealSense factory calibration data)
  fx: 420.9756774902344
  fy: 420.9756774902344
  cx: 424.884765625
  cy: 237.592529296875

